tidy up ci to ensure pinned versions of artifacts are used and checksum validation is performed where needed
Signed-off-by: Gaurav Mehta <gaurav.mehta@suse.com>

tidy up ci to ensure pinned versions of artifacts are used and checksum validation is performed where needed

Signed-off-by: Gaurav Mehta <gaurav.mehta@suse.com>
(cherry picked from commit fe9dd52f2b506e5489d66c4789b0808a71136f3d)

diff --git a/Dockerfile.dapper b/Dockerfile.dapper
--- a/Dockerfile.dapper
+++ b/Dockerfile.dapper
@@ -1,26 +1,37 @@
-FROM golang:1.25
+FROM registry.suse.com/bci/golang:1.25.7
 
 ARG DAPPER_HOST_ARCH
 ENV ARCH="$DAPPER_HOST_ARCH"
 
-RUN export K8S_VERSION=1.33.0 && \
-    curl -sSLo envtest-bins.tar.gz "https://github.com/kubernetes-sigs/controller-tools/releases/download/envtest-v${K8S_VERSION}/envtest-v${K8S_VERSION}-$(go env GOOS)-$(go env GOARCH).tar.gz" && \
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+RUN zypper -n --gpg-auto-import-keys refresh && \
+    zypper -n install bash git
+
+RUN go install github.com/mikefarah/yq/v4@v4.52.5
+## so we are going to pin it to commit hash pointing to latest release v0.20.1
+RUN curl -sSfL -o /tmp/envtest.sha https://raw.githubusercontent.com/kubernetes-sigs/controller-tools/5d9089dd33ea98f4683d6ef25a0b1363faeb8494/envtest-releases.yaml
+RUN export K8S_VERSION=v1.33.0 && \
+    export OS=$(go env GOOS) && \
+    export ARCH=$(go env GOARCH) && \
+    export ENVTEST=envtest-${K8S_VERSION}-${OS}-${ARCH}.tar.gz && \
+    echo $ENVTEST > /tmp/envtest && \
+    read -r EXPECTED_HASH < <(yq -e '.releases[env(K8S_VERSION)][env(ENVTEST)].hash' /tmp/envtest.sha) && \
+    curl -sSLo envtest-bins.tar.gz "https://github.com/kubernetes-sigs/controller-tools/releases/download/envtest-${K8S_VERSION}/envtest-${K8S_VERSION}-${OS}-${ARCH}.tar.gz" && \
+    read -r HASH < <(shasum -a 512 envtest-bins.tar.gz | awk '{print $1}') && \
+    if [ "$HASH" != "$EXPECTED_HASH" ]; then \
+        echo "Hash verification failed!"; \
+        exit 1; \
+    fi && \
     mkdir /usr/local/kubebuilder && \
     tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz && \
-    curl -sSLo kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz" && \
-    tar -C /usr/bin --strip-components=1 -zxvf kustomize.tar.gz && \
     go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.17.0
 
-RUN apt update && \
-    apt install -y bash git gcc docker.io vim less file curl wget ca-certificates qemu-utils
+RUN zypper -n install bash git gcc docker vim less file curl wget ca-certificates docker-buildx
 
 ## install golangci
-RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
+RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4
 
-# The docker version in dapper is too old to have buildx. Install it manually.
-RUN curl -sSfL https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-${ARCH} -o buildx-v0.13.1.linux-${ARCH} && \
-    chmod +x buildx-v0.13.1.linux-${ARCH} && \
-    mv buildx-v0.13.1.linux-${ARCH} /usr/local/bin/buildx
     
 ENV DAPPER_ENV="REPO TAG DRONE_TAG CROSS SKIPINDRONE"
 ENV DAPPER_SOURCE="/go/src/github.com/harvester/seeder"
